spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibertnate.ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
  mvc.view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
